env:
   global:
     - CONAN_USERNAME: rhololkeolke
     - CONAN_LOGIN_USERNAME: rhololkeolke
     - CONAN_CHANNEL: stable
     - CONAN_UPLOAD: https://api.bintray.com/conan/rhololkeolke/public-conan
     - CONAN_STABLE_BRANCH_PATTERN: stable/*
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
     - CONAN_ARCHS: x86_64
     - CONAN_BUILD_POLICY: outdated
     - CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
     - secure: "T1isErCvaY97TyoMZniKste+QLM+Vq7ocnD9TEZ369J6Mz4ayCbDJVVYi6KRPREEnICbKx/REqUEqHG7vZ/UxW46wHZLDihl086Q7vx7gpEgKXpXdHO3B3gwjkYBlWGUVsdWImcIaqkWRPfBemjG5kqRcUlLQUUSxoyOkYlG4i302GfFQ51iB/Af+T0OdEK6MX9L0U7N5iEDAheZiv1E2DurjfJABePNI7MaVUmgvuLBog5UNmznvjUsF/CTeHJ0E4wQ/27qiTjP6WLrfsV+FKSojty8FrWSkD74YAVP8hvtvBLwAhqUyjntjr8CYRU/Wc4aS1JpGO6fWsQNRJ6BErcesofTe7PRd2IVXupdXzC/XYhIWyiOPIXAtdouBQLmdv4eBEzlm/CRux8Bp2+LoJgMsySd7hK4s9WxSqZe1FPBled03m+wT/9BSIQN/plBXaUnzzK7AWGbGs+7V/H8nkDB11Q8N7mx2ABd+EFzGXYQ7mdtoSL3SlRgWMFMTTd6x/IhQ45ZNItHCbkfoSfW5yaKmpR12oH/ZtDmRtakUZSlHbUVGZHiioQARrI7G+iO/kJrRUOdXMVqUJglJSL7T9Bt+Sw7/+YJE6dNdVa+ntgWLQHg5qbbnpRwYYjrQyPTNg9wQPsCHGEEDYAf1JIEaBKlpNC/NI1fUcwBE0Lv6f8="
linux: &linux
  os: linux
  dist: xenial
  sudo: required
  language: python
  python: '3.7'
  services: 
    - docker
matrix:
  include:
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8
install:
  - chmod +x .travis/install.sh
  - "./.travis/install.sh"
script:
  - chmod +x .travis/run.sh
  - "./.travis/run.sh"
