env:
   global:
     - CONAN_USERNAME: rhololkeolke
     - CONAN_LOGIN_USERNAME: rhololkeolke
     - CONAN_CHANNEL: stable
     - CONAN_UPLOAD: https://api.bintray.com/conan/rhololkeolke/public-conan
     - CONAN_STABLE_BRANCH_PATTERN: stable/*
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
     - CONAN_ARCHS: x86_64
     - CONAN_BUILD_POLICY: outdated
     - CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
     - CONAN_TOTAL_PAGES: 8
     - secure: m41RJC7CmwYhYbDXNIPXfApmEdZHdWdOeg55o9weYk5wV/gcqjp6zqNQcAUqkyeAqJksFIBMkht4KZ3sSZKRI4bQw/ijEFmiL/WelB4iHuVkEGsw3rMgJ9KauElDHuwLSzv8D/mKn6fXWfX8TFG7aU3CzcA04x83UvZFaKOg3E5pELQ2I9FWShdVe8brm6mzgfhRL8oLe6TSSOEh4Dvbweeykb680fHjKwToh4cpdTJ+JvSr6KsHgfNqVX2HrfmOZ5zS0KgTYcKEnTcX6XNSbvkiJXEAdnHb0/W3ooRZ8HXmW/g17iAf4sgyMNBBgnAn3EOS0PaayV+i0XvN08ZMgNH7ufvbq54FZOgxM98KXGqEVjJJX0SkGY5PSOysT+jOS/edrQUE42rQrs7+jUOSy1i0yrAMicqPJfTjKCQmjgrRwa/gV+vIP23evyCd1A7W1VHwLkOAnQRNIpCafdQt4NcTCbSDisc2YE11iO2hW3AbgijV7Mv+q12SJ4htqLpKcjVQlkMFoG5reZW3xRe2shnw9Wbq+EaNsmUwFHpDVA1lf/ju4pbKIB6T/FlPHv90Z8b6LgSFCrNC56LNgwQsaRJCEkCDkvyYSRM+/kfeeZ2ipiJ0Wowy2LQExGYPnAsRpnRAhTVxz9MJpMZw6LanTBopkZlA0E4ysCpksNoK5M0=
linux: &linux
  os: linux
  dist: xenial
  sudo: required
  language: python
  python: '3.7'
  services: 
    - docker
matrix:
  include:
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-static"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-static-assimp"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-static-freetype"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-static-assimp-freetype"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-shared"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-shared-assimp"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-shared-freetype"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Release-shared-assimp-freetype"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-static"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-static-assimp"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-static-freetype"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-static-assimp-freetype"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-shared"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-shared-assimp"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-shared-freetype"
  - <<: *linux
    env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=rhololkeolke/clang8 CONAN_CURRENT_PAGE="Debug-shared-assimp-freetype"        
install:
  - chmod +x .travis/install.sh
  - "./.travis/install.sh"
script:
  - chmod +x .travis/run.sh
  - "./.travis/run.sh"
